title: Hello, world! I'm Pau Maravi
description: it's fine
permalink: ':title/'
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Pau Maraví
author-img: https://avatars2.githubusercontent.com/u/7451550?s=460&v=4
about-author: I am a software engineer
github: PauMB85
linkedin: paumaravi
email: paumb85@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
